name: Python-Flask demo
on:
  push:
    branches: 
      - main
      
jobs:
  Sample-test:
    runs-on: self-hosted
    steps:
      - name: Git Pull
        run: git pull && git checkout main

      - name: Variable to Files
        run: |
            echo "${{ vars.COMMANDS }}" > run.sh
            echo "${{ vars.NOTIFICATION }}" > notify.sh

      - name: Change the Format
        run: |
            tr -d '\r' < run.sh > fixed_run.sh
            tr -d '\r' < notify.sh > fixed_notify.sh

      - name: Run the Scripts
        run: |
            bash fixed_run.sh
            bash fixed_notify.sh 1 2 3 4 5 6 7
        

