name: Python-Flask demo
on:
  push:
    branches: 
      - main
      
jobs:
  Sample-test:
    runs-on: self-hosted
    steps:
      - name: Git Pull
        run: git pull && git checkout main

      - name: list variables
        run: echo "${{ vars.COMMANDS }}"

      - name: Run the Commands
        run: echo "${{ vars.COMMANDS }}" > test.sh

      - name: run the var
        run: |
            tr -d '\r' < test.sh > fixed_test.sh
            bash fixed_test.sh

