name: Python-Flask demo
on:
  push:
    branches: 
      - main
      
jobs:
  Sample-test:
    runs-on: self-hosted
    steps:
      - name: Git Pull
        run: git pull && git checkout "{{ github.ref_name }}"

