name: Python-Flask demo
on: [push]
jobs:
  Generate-Zap-report:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: ls
      - run: pm2 delete  python-flask
      - run: pm2 start "PORT=2020 python3 app.py" --name python-flask
      - name: Checkout zap repo
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:2020/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'


      
#      - run: pip install flask
#      - run: curl ipconfig.io
#      - run: python3 --version
#      - run: python3 app.py
