name: Python-Flask demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - run: pwd
      - run: python3 app.py
